### PR TITLE
update dependencies

### PR DESCRIPTION
**Pull request by jLopezbarb**
Update dependencies to have git 2.30.2

### CODE REVIEW

**Comment by maroshii** [comment]
Changing the base image seems like a bigger change than just updating git. Could this have other implications? Not sure of the difference between `buster` and `bullseye`

**Comment by jLopezbarb** [comment]
another approach would be running apt update at the beginning of the RUN command. Would it be better?

**Comment by maroshii** [comment]
> another approach would be running apt update at the beginning of the RUN command. Would it be better?

That's probably worse because it would make the image mutable and it could be different every time.

I'm in favor of this change and it's probably safe but I would try to understand what changes from Debian 10 to 11 (buster vs bullseye). If it bumps git I'm pretty sure other deps get updated so we should at least run a pipeline to see that all is ok

**Comment by jLopezbarb** [comment]
> Changing the base image seems like a bigger change than just updating git. Could this have other implications? Not sure of the difference between `buster` and `bullseye`

[debian `buster` does no longer fix security issues](https://endoflife.date/debian). I think we should update since we have all other images in bullseye

**Review by maroshii — APPROVED** [review]

**Comment by jLopezbarb** [comment]
Yes, but I'll wait for the next release to add it since this image has been running for the last 9 months and there can be a scenario that I didn't tested

**Pull request merged**
